export const extras = {};
// Local-only paths under the scoped dirs, declared with a reason. Empty today.

export const leftoverTokens = [
  { id: "run_in_background", re: /run_in_background/ },
  { id: "subagent_type", re: /subagent_type/ },
  { id: "askquestion", re: /AskQuestion/ },
  { id: "cursor-user-path", re: /~\/\.cursor/ },
  { id: "cursor-project-path", re: /\.cursor\// },
  { id: "create-skill", re: /create-skill/ },
  { id: "team-kit", re: /cursor-team-kit/ },
  { id: "transcripts", re: /agent-transcripts/ },
  { id: "task-tool", re: /`Task`|\bTask tool\b|\bTask subagent\b|\bTask calls\b|\bTask schema\b/ },
  { id: "loop-command", re: /`\/loop`|\/loop /, allow: ["docs/guide/10-recipes-and-pitfalls.md"] },
  { id: "update-state", re: /update_state/ },
  { id: "send-to-user", re: /SendToUser/ },
  { id: "grok-bot", re: /Grok Bot/ },
  { id: "models-mdc", re: /pstack-models\.mdc/ },
  { id: "cloud-base", re: /cloud_base_branch/ },
  { id: "cloud-env", re: /environment: "cloud"/ },
  { id: "cursor-cloud", re: /Cursor cloud agent|cloud VM|cloud-agent URL|cloud spawn|cloud root|cloud workers|cloud-sleeper|cloud default/ },
  { id: "cursor-app-support", re: /Application Support\/Cursor/ },
  { id: "cursor-builtin", re: /Cursor's built-in/ },
  { id: "cursor-mcps", re: /`mcps\/`/ },
  { id: "control-skill", re: /`control-ui`|`control-cli`/ },
  { id: "deslop-skill", re: /`\/deslop`/ },
  { id: "cloud-agent-tools", re: /Cloud-agent/ },
  { id: "automate-skill", re: /`\/automate`|`automate` skill|built-in `automate`/ },
  { id: "prefer-cursor-actions", re: /prefer_cursor_actions/ },
  { id: "cursor-slack", re: /Cursor Slack/ },
  { id: "cursor-model-picker", re: /Cursor model picker/ },
  { id: "cursor-protocol", re: /Cursor protocol/ },
  { id: "cursor-automations", re: /[Cc]ursor automations|live Cursor/ },
];
