export const overrides = {
  "skills/make-bot-ui/SKILL.md": {
    why: "The file's whole mechanism is Cursor Grok Bot routines (update_state, SendToUser secret cards, Cursor IDE chrome). Step-level substitution would touch nearly every section, so the Pi twin is hand-written; the non-mechanism sections are pinned verbatim below.",
    must: [
      "# How to make a bot UI",
      "## Host the page on this computer",
      "Bind the server to `0.0.0.0:<port>`, not `127.0.0.1`. Tailscale peers cannot reach a localhost-only bind.",
      "- method `POST`",
      "- `Content-Type: application/json`",
      "- `Authorization: Bearer <key>`",
      "- `X-Automation-Key: <key>`",
      "- timeout: 8 seconds",
      "- one try, no retry",
      "The POST returns HTTP 200 when the wake is accepted.",
      "Before you tell the user that the UI is live, probe once with a harmless payload.",
      "If a POST can fail, append the same JSON to a local log.",
      "## Put the page on the tailnet",
      "Agents on this computer share one Tailscale node. Do not create a second hostname on a node that is already online.",
      "If `tailscale status` shows an online node, skip install. Read the hostname from `tailscale status`. Read the IPv4 address from `tailscale ip -4`. Give the user both URLs:",
      "- `http://<hostname>.<tailnet>.ts.net:<port>`",
      "- `http://<100.x.x.x>:<port>`",
      "Use HTTP. Do not add HTTPS unless the user asks.",
      "curl -fsSL https://tailscale.com/install.sh | sudo sh",
      "sudo tailscale up --hostname=<short-name> --accept-dns=false --ssh=false",
      "The command prints a login URL. Send that URL to the user. The user approves the machine in the browser. Do not ask for Tailscale credentials. Do not type them.",
      "After the node is online, confirm with `tailscale status` and `tailscale ip -4`.",
      "If the login URL expires, run `tailscale up` again and send the new URL.",
    ],
  },
  "skills/setup-pstack/SKILL.md": {
    why: "The file's whole artifact is the Cursor always-applied .mdc rule; the Pi twin writes pstack-models.json, so most lines change mechanism. Non-mechanism prose is pinned verbatim below.",
    must: [
      "# Setup pstack",
      "Detect available models",
      "Load current state",
      "Budget, map, and confirm",
      "- `unlimited — keep max`",
      "- `large — xhigh reasoning`",
      "- `medium — high reasoning`",
      "- `small — medium reasoning`",
      "### 4. Validate",
      "`inherit-parent` and `auto` always pass.",
      "### 6. Confirm",
      "### 7. Offer a verification skill (optional)",
    ],
  },
};
