// Benny automations and related bindings. Keep helper L for multiline strings.
const L = (...lines) => lines.join("\n");

export const bindingsBenny = [
  {
    id: "benny-want-automations",
    why: "Cursor automations -> automations on a host the user provides",
    files: ["automations/benny/FOR_AGENTS.md"],
    find: "i want two cursor automations that work together in one slack issue channel.",
    replace: "i want two automations that work together in one slack issue channel.",
  },
  {
    id: "benny-point-cursor",
    why: "Cursor is the host today; the Pi twin is pointed by the user's agent",
    files: ["automations/benny/FOR_AGENTS.md"],
    find: "the human enters setup by pointing cursor at this file.",
    replace: "the human enters setup by pointing their agent at this file.",
  },
  {
    id: "benny-first-time-creation",
    why: "Cursor's built-in /automate and its Automations editor do not exist on Pi",
    files: ["automations/benny/FOR_AGENTS.md"],
    find: "for first-time creation, use built-in `/automate` once for triage and once for repro and fix. complete the draft review, approval, readiness check, and Automations editor handoff for the first automation before starting the second.",
    replace: "for first-time creation, create two automations on a host you provide (a scheduled job, CI workflow, or Slack bot), one for triage and one for repro and fix. complete the live-prompt review, approval, readiness check, and trigger handoff for the first automation before starting the second.",
  },
  {
    id: "benny-repo-paths-committed",
    why: "Cursor's /automate confirms committed files; the twin confirms them itself",
    files: ["automations/benny/FOR_AGENTS.md"],
    find: "use these repo-relative paths only after `/automate` confirms they are committed in the repository where the automation will run.",
    replace: "use these repo-relative paths only after you confirm they are committed in the repository where the automation will run.",
  },
  {
    id: "benny-existing-automations",
    why: "Cursor's /automate inspects and edits automations; the twin edits them on the host",
    files: ["automations/benny/FOR_AGENTS.md"],
    find: "for existing automations, do not use `/automate` to inspect or update them. validate the configuration, then use the concise field checklist in the copied setup file so i can edit each automation directly in its editor.",
    replace: "for existing automations, validate the configuration, then use the concise field checklist in the copied setup file so i can edit each automation directly on its host.",
  },
  {
    id: "benny-readme-intro",
    why: "Cursor automations -> plain automations",
    files: ["automations/benny/README.md"],
    find: "benny gives you two cursor automations for slack issue reports.",
    replace: "benny gives you two automations for slack issue reports.",
  },
  {
    id: "benny-readme-point-cursor",
    why: "Cursor is the host today; the Pi twin is pointed by the user's agent",
    files: ["automations/benny/README.md"],
    find: "1. point cursor at [`FOR_AGENTS.md`](./FOR_AGENTS.md) and name the target repository.",
    replace: "1. point your agent at [`FOR_AGENTS.md`](./FOR_AGENTS.md) and name the target repository.",
  },
  {
    id: "benny-setup-point-cursor",
    why: "Cursor is the host today; the Pi twin is pointed by the user's agent",
    files: ["automations/benny/skills/setup-benny/SKILL.md"],
    find: "The human enters setup by pointing Cursor at the pack's `FOR_AGENTS.md`.",
    replace: "The human enters setup by pointing their agent at the pack's `FOR_AGENTS.md`.",
  },
  {
    id: "benny-setup-live-automations",
    why: "Cursor Automations host -> a host the user provides",
    files: ["automations/benny/skills/setup-benny/SKILL.md"],
    find: "Benny needs external configuration and two live Cursor automations.",
    replace: "Benny needs external configuration and two live automations on a host you provide.",
  },
  {
    id: "benny-setup-before-automate",
    why: "Cursor's built-in /automate skill -> host-side creation",
    files: ["automations/benny/skills/setup-benny/SKILL.md"],
    find: "Do this before asking for Benny configuration and before invoking the built-in `/automate` skill.",
    replace: "Do this before asking for Benny configuration.",
  },
  {
    id: "benny-setup-committed-file",
    why: "Cursor's /automate confirms committed files; the twin confirms them itself",
    files: ["automations/benny/skills/setup-benny/SKILL.md"],
    find: "Reference a repository file only after the built-in `/automate` skill confirms that the file is committed in the repository where the automation runs.",
    replace: "Reference a repository file only after you confirm that the file is committed in the repository where the automation runs.",
  },
  {
    id: "benny-setup-model-slugs",
    why: "Cursor model picker -> the user's configured providers",
    files: ["automations/benny/skills/setup-benny/SKILL.md"],
    find: "Use only model slugs shown as available in the user's Cursor model picker or supported model list.",
    replace: "Use only model slugs available in the user's configured providers.",
  },
  {
    id: "benny-setup-slack-actions",
    why: "Cursor Slack actions -> the host's configured Slack actions",
    files: ["automations/benny/skills/setup-benny/SKILL.md"],
    find: "Prefer configured Cursor Slack actions for reads and posts.",
    replace: "Prefer the host's configured Slack actions for reads and posts.",
  },
  {
    id: "benny-setup-first-time-block",
    why: "Cursor's built-in /automate skill and its Automations-editor handoff do not exist on Pi; the twin creates each automation on a host the user provides",
    files: ["automations/benny/skills/setup-benny/SKILL.md"],
    find: L(
      "5. Read and follow the built-in `automate` skill.",
      "6. Let `automate` discover Slack channels, the repository, and connected integrations.",
      "7. Let `automate` confirm that the copied pack and any referenced configuration files are committed in the same repository where the automation will run.",
      "8. Let `automate` show its draft table, obtain approval, ask readiness, and open the Automations editor.",
      "9. Finish the editor handoff for this automation before starting the next one.",
      "",
      "Give `automate` this complete triage intent, filled from configuration:",
      "",
      "- Name `benny-triage`.",
      "- Read and follow `.pi/automations/benny/skills/triage-issue-reports/SKILL.md` for every run.",
      "- Trigger on each new top-level report in the configured source Slack channel.",
      "- Read the triggering thread and reply only inside it.",
      "- Use the configured issue-tracker integration.",
      "- Classify, inspect evidence, trace cause, dedupe, and create only clear new bugs.",
      "- End one thread-only verdict with the configured `[benny:bug]`, `[benny:performance]`, or `[benny:other]` marker and optional tracker URL.",
      "- Never post a source-channel root message.",
      "",
      "After the triage editor handoff is complete, give `automate` this complete repro and fix intent:",
      "",
      "- Name `benny-reproduce`.",
      "- Read and follow `.pi/automations/benny/skills/reproduce-and-fix-issues/SKILL.md` for every run.",
      "- Trigger on the same new top-level reports in the configured source Slack channel.",
      "- Use the configured repository and default branch.",
      "- Read the source thread and reply only inside it.",
      "- Include pull request creation and the configured tracker, control-adapter, and feature-map requirements. Paraphrase mapped user paths and states unless `automate` confirms an eligible committed file in the same repository.",
      "- Wait for a trusted triage marker before acting.",
      "- Reproduce the exact symptom twice through the mapped real UI and capture evidence.",
      "- Verify an existing fix without authoring over it.",
      "- Attempt an optional bounded fix only after confirmed repro, then open a draft pull request when proof and checks pass.",
      "- Never post a source-channel root message.",
      "",
      "Do not duplicate `automate`'s Slack, repository, integration, completeness, authentication, draft-review, approval, readiness, or editor-handoff work.",
    ),
    replace: L(
      "5. Create the automation on the host with a live prompt that reads the committed operational file.",
      "6. Give the host's Slack integration source-channel, thread-read, and thread-reply permissions.",
      "7. Confirm the copied pack and referenced configuration are committed in the same repository.",
      "8. Review the live prompt, obtain approval, and check readiness before enabling.",
      "9. Finish this automation's handoff before starting the next.",
      "",
      "Give the triage automation this complete intent, filled from configuration:",
      "",
      "- Name `benny-triage`.",
      "- Read and follow `.pi/automations/benny/skills/triage-issue-reports/SKILL.md` for every run.",
      "- Trigger on each new top-level report in the configured source Slack channel.",
      "- Read the triggering thread and reply only inside it.",
      "- Use the configured issue-tracker integration.",
      "- Classify, inspect evidence, trace cause, dedupe, and create only clear new bugs.",
      "- End one thread-only verdict with the configured `[benny:bug]`, `[benny:performance]`, or `[benny:other]` marker and optional tracker URL.",
      "- Never post a source-channel root message.",
      "",
      "After the triage handoff is complete, give the repro automation this complete intent:",
      "",
      "- Name `benny-reproduce`.",
      "- Read and follow `.pi/automations/benny/skills/reproduce-and-fix-issues/SKILL.md` for every run.",
      "- Trigger on the same new top-level reports in the configured source Slack channel.",
      "- Use the configured repository and default branch.",
      "- Read the source thread and reply only inside it.",
      "- Include pull request creation and the configured tracker, control-adapter, and feature-map requirements. Paraphrase mapped user paths and states unless you confirm an eligible committed file in the same repository.",
      "- Wait for a trusted triage marker before acting.",
      "- Reproduce the exact symptom twice through the mapped real UI and capture evidence.",
      "- Verify an existing fix without authoring over it.",
      "- Attempt an optional bounded fix only after confirmed repro, then open a draft pull request when proof and checks pass.",
      "- Never post a source-channel root message.",
      "",
      "Host setup is yours to finish. Do not duplicate the host's Slack, repository, integration, completeness, authentication, review, approval, readiness, or handoff work.",
    ),
  },
  {
    id: "benny-setup-creation-only",
    why: "Cursor's /automate is creation-only; the twin creates nothing on inspection",
    files: ["automations/benny/skills/setup-benny/SKILL.md"],
    find: "The built-in `automate` skill is creation-only. Do not use it to search for, inspect, or update existing automations.",
    replace: "Do not search for, inspect, or update existing automations through a creation tool.",
  },
  {
    id: "benny-setup-host-checklist",
    why: "Cursor's Automations editor -> the host's own editor",
    files: ["automations/benny/skills/setup-benny/SKILL.md"],
    find: "Then give the user this concise editor checklist.",
    replace: "Then give the user this concise host checklist.",
  },
  {
    id: "benny-setup-editor-to-host",
    why: "Cursor's Automations editor -> the host's own editor",
    files: ["automations/benny/skills/setup-benny/SKILL.md"],
    find: "Ask the user to update each existing automation directly in its Automations editor.",
    replace: "Ask the user to update each existing automation directly on its host.",
  },
  {
    id: "benny-setup-deep-link",
    why: "Cursor protocol deep links and the /automate editor handoff do not exist on Pi",
    files: ["automations/benny/skills/setup-benny/SKILL.md"],
    find: "Never build or open a Cursor protocol deep link. For new automations, the only finish path is the built-in `automate` skill's reviewed Automations editor handoff.",
    replace: "Never build or open a host-specific deep link. For new automations, the only finish path is a reviewed handoff on the host you chose.",
  },
  {
    id: "benny-setup-thread-safety",
    why: "Cursor's Automations editor save -> the host save",
    files: ["automations/benny/skills/setup-benny/SKILL.md"],
    find: "Do not enable either automation until the thread-safety test passes after the editor save.",
    replace: "Do not enable either automation until the thread-safety test passes after the host save.",
  },
  {
    id: "benny-repro-slack-actions",
    why: "Cursor Slack actions -> the host's configured Slack actions",
    files: ["automations/benny/skills/reproduce-and-fix-issues/SKILL.md"],
    find: "Prefer configured Cursor Slack actions.",
    replace: "Prefer the host's configured Slack actions.",
  },
  {
    id: "benny-config-host-actions",
    why: "prefer_cursor_actions selects Cursor Slack actions; the twin uses the host's",
    files: ["automations/benny/templates/configuration.example.yaml"],
    find: "prefer_cursor_actions: true",
    replace: "prefer_host_actions: true",
  },
  {
    id: "benny-template-blockquote",
    why: "Cursor's built-in /automate draft -> the live prompt on the user's host",
    files: ["automations/benny/templates/triage-automation-prompt.md", "automations/benny/templates/reproduce-automation-prompt.md"],
    find: "Paraphrase this intent into a built-in `automate` draft after `automate` confirms that the copied pack is committed in the repository where the automation will run.",
    replace: "Paraphrase this intent into the live prompt on your host after you confirm that the copied pack is committed in the repository where the automation will run.",
  },
];
